### ISSUE TITLE
Nodegit is lost when pushing from inside a submodule

### ISSUE THREAD

**Issue by divarvel** [CleverCloud/clever-tools#135] opened 2017-06-07 09:12 UTC

**Comment by hsablonniere** [comment] 2018-01-08 08:55
I was not able to reproduce this. I tried a `clever deploy` inside a submodule. Can you give more details?

**Comment by hsablonniere** [comment] 2018-10-15 15:59
I'm closing the issue, I wasn't able to reprodure with 0.10.1 (NodeGit) and we don't have NodeGit anymore.

**Closed by hsablonniere** 2018-10-15 15:59 UTC
