### ISSUE TITLE
`clever deploy` not exiting on deployment success

### ISSUE THREAD

**Issue by clementd-fretlink** [CleverCloud/clever-tools#294] opened 2018-11-22 11:06 UTC
We are migrating our CI to `v1.1.1` and we observed that `clever deploy` did not exit upon deployment success.

Looking at the code in the stream command handler, I see an explicit `process.exit` for errors, but not for the end of the stream. [0]

I've witnessed a few times with bacon that sometimes the process keeps running even though we've got to the end of a stream. I guess it's because there is still an active event listener registered somewhere.

In the case of `clever deploy` (or `clever restart`), i feel that an explicit exit at the end of the deployment would be safer_

[0]: https://github.com/CleverCloud/clever-tools/blob/master/src/command-stream-handler.js#L6

**Comment by clementd-fretlink** [comment] 2018-11-22 11:08
(this issue is currently preventing us to migrate to `v1.10`)

**Comment by hsablonniere** [comment] 2018-11-27 22:23
I'll look into it. I'm curious about why you have this problem and I don't reproduce it on test apps.

**Comment by divarvel** [comment] 2018-11-27 22:34
It only happens in the CI environment, but it's not the first time I see
apps hanging this way (ask @juuduu, I know he's had the problem on a JS app
using cliparse).

In any case, being explicit for exit conditions is a good thing

Le 27 nov. 2018 23:23, "Hubert SABLONNIÈRE" <notifications@github.com> a
écrit :

I'll look into it. I'm curious about why you have this problem and I don't
reproduce it on test apps.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CleverCloud/clever-tools/issues/294#issuecomment-442240719>,
or mute the thread

**Comment by hsablonniere** [comment] 2018-11-30 16:02
I'll check some details with @judu next week and we'll try to do it next week.

**Comment by clementd-fretlink** [comment] 2018-11-30 16:04
See maybe #296 which could be related.
But nevertheless, an explicit exit is always a good thing.

**Comment by divarvel** [comment] 2019-01-02 13:40
👌

**Comment by hsablonniere** [comment] 2019-01-02 15:16
Fixed by #299, I'll have a look at #296 and #297 before doing a release.
Do you want a beta release to try the fix?

**Comment by haitlahcen** [comment] 2019-01-02 15:36
I already tested the application with the exact same patch. The problem seems to be #296 which indefinitely try to reconnect when network access is forbidden. This has the consequence of producing an infinite stream, and the aforementioned patch will not help in that specific case.

**Comment by hsablonniere** [comment] 2019-01-02 16:38
@haitlahcen What do you mean by "when network access is forbidden"?

Can I reproduce the neverending command by trying to deploy to a repo I don't have access to? :thinking:

**Comment by haitlahcen** [comment] 2019-01-02 16:48
I our case, for some reasons, the host was unreachable (clever cloud). Thus, the application was indefinitely trying to reconnect every 1.5s.

**Comment by hsablonniere** [comment] 2019-01-02 16:50
@haitlahcen OK, thanks.

**Closed** 2019-01-11 14:31 UTC
