### ISSUE TITLE
Deploy commit from a tag

### ISSUE THREAD

**Issue by sebartyr** [CleverCloud/clever-tools#543] opened 2022-10-19 14:09 UTC
Some users would like to push a tag instead of a branch because tags is a way to label versions.
For now, push a tag does not trigger a deployment on Clever Cloud
The trick could be :
- create a new branch from the commit labeled with the tag  
- push this branch into master
- delete the branch

It could be interesting to do so with `clever deploy` :
`clever deploy --tag <tagname>`

**Comment by aurrelhebert** [comment] 2023-07-25 14:14
Closing it as it's a duplicate of https://github.com/CleverCloud/clever-tools/issues/265

**Comment by aurrelhebert** [comment] 2023-07-25 14:14
Closing it as it's a duplicate of https://github.com/CleverCloud/clever-tools/issues/265

**Closed by aurrelhebert** 2023-07-25 14:14 UTC
Labels: command:deploy
